# Generated by Django 4.2.3 on 2023-07-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_choice_text_choice_name_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='name_text',
            new_name='choice_text',
        ),
    ]
